// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { ThemePreference } from "./ThemePreference";

export type Settings = { schemaVersion: number, hotkey: string, autoPaste: boolean, theme: ThemePreference, };
