// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TemplateSummary = { id: string, displayName: string, isPinned: boolean, tags: Array<string>, };
