// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import type { Variable } from "./Variable";

export type Template = { schemaVersion: number, id: string, displayName: string, body: string, variables: Array<Variable>, tags: Array<string>, isPinned: boolean, createdAt: string, updatedAt: string, lastUsedAt: string | null, useCount: number, };
