// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `apply_template`. Tells the frontend whether autoPaste ran and,
 * if it didn't, why (so toast wording can differ).
 */
export type ApplyOutcome = { 
/**
 * true → auto-pasted into the previously-focused window;
 * false → clipboard-only.
 */
pasted: boolean, 
/**
 * "disabled" if autoPaste setting is off; "failed" if it was attempted
 * but errored (HWND invalid, OS refused focus, etc.). null when pasted=true.
 */
reason: string | null, };
