// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of inspecting a candidate folder for the onboarding flow.
 * SPEC §11 三选一: "default new" / "custom new" / "import existing".
 */
export type DataFolderStatus = "doesNotExist" | "empty" | "validSnippet" | "occupiedByOther";
