// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Template } from "./Template";
import type { Variable } from "./Variable";

export type FillDialogState = { template: Template, initialValues: { [key in string]?: string }, orderedVariables: Array<Variable>, };
