// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A warning collected during app startup (corrupt config recovered, hotkey
 * registration failed, etc.) that should be shown to the user via toast.
 */
export type StartupWarning = { 
/**
 * Machine-readable category: "corrupt_config", "invalid_templates",
 * "hotkey_failed", "write_permission".
 */
kind: string, 
/**
 * Human-readable message (Chinese) shown to the user.
 */
message: string, };
