// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VariableType } from "./VariableType";

export type Variable = { guid: string, displayName: string, type: VariableType, options: Array<string> | null, required: boolean, fillFromClipboard: boolean, rememberLastUsed: boolean, staticDefault: string | null, };
